version: "3.8"

services:
  xk-app:
    image: xk-app:v${BUILD_VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 6909:6909
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
