version: "3.8"

services:
  xk-app:
    image: xk-app:v${BUILD_VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5282:5282
